name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  abi-up-to-date:
    name: Check ABI files are up-to-date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ensure `./wit/deps` are in sync
      run: |
        curl -Lo 'wit-deps' https://github.com/bytecodealliance/wit-deps/releases/download/v0.5.0/wit-deps-x86_64-unknown-linux-musl
        chmod +x ./wit-deps
        ./wit-deps lock --check
        ./wit-deps -m wit-0.3.0-draft/deps.toml -l wit-0.3.0-draft/deps.lock -d wit-0.3.0-draft/deps lock --check
    - uses: WebAssembly/wit-abi-up-to-date@v22
      with:
        wasm-tools: '1.223.0'
        wit-bindgen: '0.37.0'
        worlds: 'imports proxy'
